name: Flutter APK Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Base Flutter Template
        run: |
          # 1. මුලින්ම ඇප් එක Build කිරීමට අවශ්‍ය මූලික Android ෆයිල්ස් ඔටෝ සාදා ගැනීම
          flutter create --org com.garmex.ytclone --project-name youtube_premium_clone . --force

      - name: Checkout Code Override
        uses: actions/checkout@v4
        with:
          path: 'temp_src'

      - name: Copy Custom Code Over Template
        run: |
          # 2. ඔබ සෑදූ main.dart සහ pubspec.yaml ෆයිල්ස් නිවැරදි තැන්වලට කොපි කිරීම
          cp -f temp_src/pubspec.yaml ./pubspec.yaml
          cp -f temp_src/lib/main.dart ./lib/main.dart

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-premium-apk
          path: build/app/outputs/flutter-apk/app-release.apk
