name: Flutter APK Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          path: 'temp_src'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Base Flutter Template
        run: |
          flutter create --org com.garmex.ytclone --project-name youtube_premium_clone .

      - name: Apply Custom Code
        run: |
          cp -f temp_src/pubspec.yaml ./pubspec.yaml
          cp -f temp_src/lib/main.dart ./lib/main.dart

      - name: Install dependencies
        run: flutter pub get

      # Google හි නවතම Android පද්ධති නීති නිසා සිදුවන බිඳවැටීම ස්වයංක්‍රීයව නිවැරදි කිරීමේ පියවර
      - name: Fix Android Proguard Issue
        run: |
          find ~/.pub-cache/ -name "build.gradle" -exec sed -i "s/proguard-android.txt/proguard-android-optimize.txt/g" {} +

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-premium-apk
          path: build/app/outputs/flutter-apk/app-release.apk
